#!/bin/sh
if [[ -f /tmp/OneOdio ]]; then
    bluetoothctl disconnect 37:91:84:52:98:26 && \
    rm /tmp/OneOdio && \
    notify-send "Disconnected successfully" || \
    notify-send "Disconnection failed"
else
    bluetoothctl scan on
    bluetoothctl connect 37:91:84:52:98:26 && \
    touch /tmp/OneOdio && \
    notify-send "Connected successfully" || notify-send "Connection failed"
    bluetoothctl scan off
fi
