#!/bin/bash

VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | cut -d' ' -f2)

if [[ $VOLUME == 0.00 ]];then
	if [[ -f /tmp/precvol ]]; then
		VOLUME=$(cat /tmp/precvol)
		wpctl set-volume @DEFAULT_AUDIO_SINK@ $VOLUME
	fi
else
	echo $VOLUME > /tmp/precvol
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 0

fi

	
